name = "OscillatorProdDemo"
uuid = "8e1f2a3b-3c4d-5e6f-7a8b-9c0d1e2f3a4b"
authors = ["Modelling in Physics"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a1-8c61-6b8b8b8b8b8b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
